# Generated by Django 4.1.3 on 2022-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf_candidato', models.CharField(max_length=11, verbose_name='CPF')),
                ('nasc_candidato', models.DateField(verbose_name='Data de nascimento: ')),
                ('email_candidato', models.EmailField(max_length=254)),
                ('endereco_candidato', models.CharField(max_length=255)),
                ('genero_candidato', models.CharField(blank=True, max_length=50)),
                ('curso_candidato', models.CharField(choices=[('Curso técnico', 'Curso técnico'), ('ADS', 'ADS')], max_length=50)),
                ('mini_cursos', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
