# Generated by Django 4.1.3 on 2022-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf_candidato',
            field=models.CharField(max_length=11, verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso_candidato',
            field=models.CharField(choices=[('Curso técnico', 'Curso técnico'), ('ADS', 'ADS')], max_length=50, verbose_name='Curso:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email_candidato',
            field=models.EmailField(max_length=254, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco_candidato',
            field=models.CharField(max_length=255, verbose_name='Endereço:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='genero_candidato',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='mini_cursos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mini cursos'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome_candidato',
            field=models.CharField(max_length=100, verbose_name='Nome:'),
        ),
    ]
