# Generated by Django 4.1.3 on 2022-11-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_alter_candidato_cpf_candidato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='genero_candidato',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50, verbose_name='Sexo:'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='mini_cursos',
            field=models.CharField(blank=True, choices=[('Introdução a Computação Gráfica', 'Introdução a Computação Gráfica'), ('Introdução a construção de jogos', 'Introdução a construção de jogos'), ('Minicurso de Realidade Virtual', 'Minicurso de Realidade Virtual'), ('Computação nas Nuvens', 'Computação nas Nuvens')], max_length=100, verbose_name='Mini cursos'),
        ),
    ]
